pipeline{
    agent{label "javanode"}
    tools {maven 'maventool'}

    stages{
        stage('Build'){
            steps{
                sh 'mvn clean install'
            }
        }

        stage('Build docker image'){
                    steps{
                        script{
                            sh 'docker build -t javatechie/devops-integration .'
                        }
                    }
        }
    }
}