pipeline{
    agent {label 'mavenjob'}
    tools {maven 'maventool'}
    stages {
        stage ('checkout') {
            steps {
                checkout scm
            }
            
        }
        stage ('Build'){
            steps{
                sh 'mvn clean install'
            }
        }
            
        }
    }